import { CompletionItemKind, CompletionItem } from 'vscode-languageserver';

export const builtIn = 'builtIn';
export const iterator = 'iterator';
export const languageServer = 'kos-language-server';

export const keywords = new Set([
  'add',
  'and',
  'all',
  'at',
  'break',
  'clearscreen',
  'compile',
  'copy',
  'do',
  'declare',
  'defined',
  'delete',
  'edit',
  'else',
  'false',
  'file',
  'for',
  'from',
  'function',
  'global',
  'if',
  'in',
  'is',
  'lazyglobal',
  'list',
  'local',
  'lock',
  'log',
  'not',
  'off',
  'on',
  'or',
  'once',
  'parameter',
  'preserve',
  'print',
  'reboot',
  'remove',
  'rename',
  'return',
  'run',
  'runpath',
  'runoncepath',
  'set',
  'shutdown',
  'stage',
  'step',
  'switch',
  'then',
  'to',
  'true',
  'toggle',
  'unlock',
  'unset',
  'until',
  'volume',
  'wait',
  'when',
]);

export const keywordCompletions: CompletionItem[] = Array.from(keywords)
  .map(keyword => ({
    kind: CompletionItemKind.Keyword,
    label: keyword,
    data: undefined,
  }));
