# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- development

pool:
  vmImage: 'Ubuntu-16.04'

# setup node
steps:
- checkout: self
  submodules: 'true'
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# install node dependencies and compile with typescript
- script: |
    npm install
    npm run prod
  displayName: 'npm install and compile'

# run test
- script: npx jest --ci --config server/jest.config.js
  displayName: 'jest test runner'

# publish test results
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '$(System.DefaultWorkingDirectory)/junit.xml'

# publish coverage results
- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/server/src/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/server/src/coverage'

# publish folder
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)'
